
export default {
  $schema: "https://json.schemastore.org/prettierrc",
  arrowParens: "always",
  bracketSpacing: false,
  printWidth: 150,
  semi: false,
  singleQuote: false,
  tabWidth: 2,
  trailingComma: "all",
  importOrderParserPlugins: ["typescript"],
  importOrderTypeScriptVersion: "5.0.0",
  importOrderParserPlugins: ["typescript"],
  importOrderTypeScriptVersion: "5.0.0",
  plugins: ["@ianvs/prettier-plugin-sort-imports"],
  importOrder: [
    "^@daily/(.*)$",
    "",
    "^vue$",
    "^vue-(.*)$",
    "^@vueuse/(.*)$",
    "<THIRD_PARTY_MODULES>",
    "",
    "^@/api(.*)$",
    "^@/utils(.*)$",
    "^@/constants(.*)$",
    "^@/composables(.*)$",
    "^@/stores(.*)$",
    "^@/ui(.*)$",
    "^(?!.*)[./].*$",
    "^[./]",
    "",
    "<TYPES>",
    "<TYPES>^[.]",
  ],
};
